sonar.projectKey=Marco_Soto_t1
sonar.host.url=https://sonarqube.ingsoftware.lat/

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,.pytest_cache/**,.mypy_cache/**,.ruff_cache/**,.scannerwork/**,.venv/**,openspec/**,docs/**,*.pdf,coverage.xml
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11,3.12
